language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
before_install:
  sudo apt-get install sshpass libmagic-dev
install:
  "pip install -r requirements.txt"
# command to run tests
script:
  python run_tests.py
  #python run_tests.py & nosetests --with-coverage
after_success:
  sshpass -p 0TUDSJdJe6ZBvCXa5yUi ssh -o StrictHostKeyChecking=no root@mynstu.xyz "cd /var/www/stud-nstu && find . -type f -name "*.pyc" -exec rm -f {} \; && git pull origin master && service httpd restart"
sudo:
  true
notifications:
  slack: russian-beavers:5fVhZfBTN0tfbCuu0eACKrjt